// <auto-generated />
using System;
using InventarioBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventarioBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250727225139_InventarioApp")]
    partial class InventarioApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventarioBackend.Models.InventarioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaRegistroItem")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoActual")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoProducto");

                    b.ToTable("InventarioItems");
                });

            modelBuilder.Entity("InventarioBackend.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<decimal>("CantidadPeso")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdItem");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("InventarioBackend.Models.TipoProducto", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipo"));

                    b.Property<decimal?>("Ancho")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Calibre")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Largo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Medida")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mezcla")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Toquel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnidadPeso")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTipo");

                    b.ToTable("TiposProducto");
                });

            modelBuilder.Entity("InventarioBackend.Models.InventarioItem", b =>
                {
                    b.HasOne("InventarioBackend.Models.TipoProducto", "TipoProducto")
                        .WithMany("InventarioItems")
                        .HasForeignKey("IdTipoProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoProducto");
                });

            modelBuilder.Entity("InventarioBackend.Models.MovimientoInventario", b =>
                {
                    b.HasOne("InventarioBackend.Models.InventarioItem", "InventarioItem")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventarioItem");
                });

            modelBuilder.Entity("InventarioBackend.Models.InventarioItem", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("InventarioBackend.Models.TipoProducto", b =>
                {
                    b.Navigation("InventarioItems");
                });
#pragma warning restore 612, 618
        }
    }
}
